name: umami
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-v2.12.1
    container_name: umami
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db-pg16:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: ${APP_SECRET}
    networks:
      - traefik
      - umami
    depends_on:
      db-pg16:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      traefik.enable: true
      traefik.http.routers.umami.rule: "Host(`umami.lab.beyerleinf.de`)"
      traefik.http.routers.umami.entrypoints: "websecure"
      traefik.http.routers.umami.tls.certresolver: "hetzner"
      traefik.http.services.umami.loadbalancer.server.port: 3000

  db-pg16:
    image: postgres:16.6-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - umami-db-data-pg16:/var/lib/postgresql/data
    networks:
      - umami
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-backup:
    image: tiredofit/db-backup:4.1.12
    environment:
      TIMEZONE: "Europe/Berlin"
      MODE: "MANUAL"
      MANUAL_RUN_FOREVER: false
      CONTAINER_ENABLE_SCHEDULING: false
      CONTAINER_ENABLE_MONITORING: false
      BACKUP_JOB_CONCURRENCY: 1
      DEFAULT_COMPRESSION: "GZ"
      DEFAULT_GZ_RSYNCABLE: true
      DEFAULT_S3_BUCKET: ${S3_BUCKET_NAME}
      DEFAULT_S3_KEY_ID: ${S3_BUCKET_KEY_ID}
      DEFAULT_S3_KEY_SECRET: ${S3_BUCKET_KEY_SECRET}
      DEFAULT_S3_REGION: ${S3_BUCKET_REGION}
      DEFAULT_S3_HOST: ${S3_BUCKET_HOST}
      ENABLE_NOTIFICATIONS: true
      NOTIFICATION_TYPE: "MATRIX"
      MATRIX_HOST: ${MATRIX_HOST}
      MATRIX_ROOM: ${MATRIX_ROOM}
      MATRIX_ACCESS_TOKEN: ${MATRIX_ACCESS_TOKEN}
      DB01_TYPE: "pgsql"
      DB01_HOST: "db-pg16"
      DB01_NAME: "umami"
      DB01_SPLIT_DB: true
      DB01_BACKUP_LOCATION: "S3"
      DB01_USER: ${DB_USER}
      DB01_PASS: ${DB_PASSWORD}
      DB01_S3_PATH: "db/umami"
      DB01_CLEANUP_TIME: 40320 # 28 days
    networks:
      - umami

volumes:
  umami-db-data-pg16:

networks:
  traefik:
    name: traefik
    external: true
  umami:
    name: umami
