name: umami
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-v2.12.1
    container_name: umami
    ports:
      - 3331:3000
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db-pg16:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: ${APP_SECRET}
    networks:
      - traefik
      - umami
    depends_on:
      db-pg16:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umami.rule=Host(`umami.lab.beyerleinf.de`)"
      - "traefik.http.routers.umami.entrypoints=websecure"
      - "traefik.http.routers.umami.tls.certresolver=hetzner"

  db-pg16:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - umami-db-data-pg16:/var/lib/postgresql/data
    networks:
      - umami
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  umami-db-data-pg16:

networks:
  traefik:
    name: traefik
    external: true
  umami:
    name: umami
