name: grafana
services:
  grafana:
    image: grafana/grafana:11.2.0
    depends_on:
      - prometheus
    ports:
      - "3033:3000"
    volumes:
      - ${GRAFANA_DATA_DIR}:/var/lib/grafana
      - ${GRAFANA_DIR}/provisioning:/etc/grafana/provisioning/
    environment:
      GF_USERS_ALLOW_SIGN_UP: false
    networks:
      - grafana

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ${PROMETHEUS_DATA_DIR}:/prometheus
      - ${PROMETHEUS_DIR}:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor
      - node-exporter
    networks:
      - grafana
      - traefik

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - grafana
    command:
      - "-housekeeping_interval=30s"
      - "-docker_only=true"

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - grafana

networks:
  grafana:
    name: grafana
  traefik:
    external: true
