name: grafana
services:
  grafana:
    image: grafana/grafana:11.5.0
    restart: always
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - ${GRAFANA_DATA_DIR}:/var/lib/grafana
      - ${GRAFANA_DIR}/provisioning:/etc/grafana/provisioning/
    environment:
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SERVER_DOMAIN: "grafana.lab.beyerleinf.de"
      GF_SERVER_ROOT_URL: "https://grafana.lab.beyerleinf.de"
    networks:
      - grafana
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.grafana.rule: "Host(`grafana.lab.beyerleinf.de`)"
      traefik.http.routers.grafana.entrypoints: "websecure"
      traefik.http.routers.grafana.tls.certresolver: "hetzner"
      traefik.http.services.grafana.loadbalancer.server.port: 3000

  prometheus:
    image: prom/prometheus:v3.2.1
    restart: always
    volumes:
      - ${PROMETHEUS_DATA_DIR}:/prometheus
      - ${PROMETHEUS_DIR}:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor
      - node-exporter
    networks:
      - grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    restart: always
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - grafana
    command:
      - "-housekeeping_interval=30s"
      - "-docker_only=true"

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.9.0
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - grafana

networks:
  grafana:
    name: grafana
  traefik:
    external: true
