name: firefly
services:
  firefly:
    container_name: firefly
    restart: always
    image: fireflyiii/core:version-6.1.19
    networks:
      - traefik
      - firefly
    volumes:
      - upload:/var/www/html/storage/upload
    depends_on:
      - db
    environment:
      APP_ENV: "production"
      APP_KEY: ${APP_KEY}
      APP_URL: "https://firefly.lab.beyerleinf.de"
      DEFAULT_LANGUAGE: "en_US"
      TZ: "Europe/Berlin"
      TRUSTED_PROXIES: "**"
      DB_CONNECTION: "mysql"
      DB_HOST: "db"
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      STATIC_CRON_TOKEN: ${STATIC_CRON_TOKEN}
    labels:
      traefik.enable: true
      traefik.http.routers.firefly.rule: "Host(`firefly.lab.beyerleinf.de`)"
      traefik.http.routers.firefly.entrypoints: "websecure"
      traefik.http.routers.firefly.tls.certresolver: "hetzner"
      traefik.http.services.firefly.loadbalancer.server.port: 8080

  db:
    image: mariadb:11.6.2
    restart: always
    networks:
      - firefly
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  importer:
    image: fireflyiii/data-importer:version-1.5.5
    hostname: importer
    restart: always
    networks:
      - firefly
    depends_on:
      - firefly
    ports:
      - "8086:8080"
    environment:
      FIREFLY_III_URL: "firefly:8080"
      VANITY_URL: "https://firefly.lab.beyerleinf.de"
      FIREFLY_III_ACCESS_TOKEN: ${FIREFLY_ACCESS_TOKEN}
      NORDIGEN_ID: ${GO_CARDLESS_ID}
      NORDIGEN_KEY: ${GO_CARDLESS_KEY}
      RESPOND_TO_GOCARDLESS_LIMIT: "wait"
      GOCARDLESS_GET_ACCOUNT_DETAILS: false # unused
      TZ: "Europe/Berlin"
      TRUSTED_PROXIES: "**"

  cron:
    image: alpine:3.21.2
    restart: always
    command: sh -c "echo \"0 3 * * * wget -qO- http://firefly:8080/api/v1/cron/${STATIC_CRON_TOKEN}\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly

volumes:
  upload:
  db:

networks:
  firefly:
    name: firefly
  traefik:
    external: true
