name: grocy
services:
  grocy:
    image: linuxserver/grocy:4.3.0
    restart: always
    container_name: grocy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Europe/Berlin"
    volumes:
      - ${GROCY_DIR}:/config
    networks:
      - traefik
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      traefik.enable: true
      traefik.http.routers.grocy.rule: "Host(`grocy.lab.beyerleinf.de`)"
      traefik.http.routers.grocy.entrypoints: "websecure"
      traefik.http.routers.grocy.tls.certresolver: "hetzner"
      traefik.http.services.grocy.loadbalancer.server.port: 80

networks:
  traefik:
    external: true
