---
# tasks file for beyerleinf.homelab.metallb

- name: Apply MetalLB manifest
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml
    apply: true

- name: Deploy IP Address Pool
  block:
    - name: Create IP Address Pool manifest
      ansible.builtin.template:
        src: ipaddresses.yml.j2
        dest: /tmp/ipaddresses.yml
        mode: "0644"

    - name: Apply IP Address Pool manifest
      kubernetes.core.k8s:
        state: present
        src: /tmp/ipaddresses.yml

- name: Deploy Layer2 Config
  block:
    - name: Create Layer2 Config manifest
      ansible.builtin.template:
        src: layer2.yml.j2
        dest: /tmp/layer2.yml
        mode: "0644"

    - name: Apply Layer2 Config manifest
      kubernetes.core.k8s:
        state: present
        src: /tmp/layer2.yml
