name: actual
services:
  actual:
    container_name: actual
    image: ghcr.io/actualbudget/actual-server:24.9.0-alpine
    volumes:
      - ${DOCKER_DIR}:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual.rule=Host(`budget.lab.beyerleinf.de`)"
      - "traefik.http.routers.actual.entrypoints=websecure"
      - "traefik.http.routers.actual.tls.certresolver=hetzner"
      - "traefik.http.services.actual.loadbalancer.server.port=5006"

networks:
  traefik:
    external: true
