apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /app/config/confg.yml
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: homepage-config
