services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.2
    container_name: homepage
    networks:
      - reverseproxy
    ports:
      - 3003:3000
    volumes:
      - ${DOCKER_DIR}:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  homepage:

networks:
  reverseproxy:
    name: reverseproxy
    external: true
