name: "homeassistant"
services:
  homeassistant:
    container_name: "homeassistant"
    privileged: true
    image: ghcr.io/home-assistant/home-assistant:2025.2
    volumes:
      - /run/dbus:/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/ttyACM0:/dev/ttyACM0
      - ${HASS_DOCKER_DIR}:/config
    networks:
      - traefik
      - homeassistant
    depends_on:
      - mqtt
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.homeassistant.rule: "Host(`hass.lab.beyerleinf.de`)"
      traefik.http.routers.homeassistant.entrypoints: "websecure"
      traefik.http.routers.homeassistant.tls.certresolver: "hetzner"
      traefik.http.services.homeassistant.loadbalancer.server.port: 8123

  mqtt:
    image: eclipse-mosquitto:2.0.20
    ports:
      - "1883:1883"
    volumes:
      - ${MQTT_DOCKER_DIR}:/mosquitto
    networks:
      - homeassistant
    restart: always

networks:
  homeassistant:
    name: homeassistant
  traefik:
    external: true
