---
- name: Stop and disable snapd
  ansible.builtin.systemd:
    name: snapd
    state: stopped
    enabled: false
    masked: true

- name: Purge snapd
  ansible.builtin.apt:
    name: multipath-tools
    state: absent
    purge: true

- name: Hold snapd
  ansible.builtin.dpkg_selections:
    name: multipath-tools
    selection: hold

- name: Remove snapd directory
  become: true
  ansible.builtin.file:
    state: absent
    path: ~/snap/
