---
- name: Check if multipathd is installed
  ansible.builtin.shell: dpkg -l | grep -q multipath-tools
  register: multipathd_installed
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Stop and disable multipathd
  ansible.builtin.systemd:
    name: multipathd
    state: stopped
    enabled: false
    masked: true
  when: multipathd_installed.rc == 0

- name: Purge multipathd
  ansible.builtin.apt:
    name: multipath-tools
    state: absent
    purge: true
  when: multipathd_installed.rc == 0

- name: Hold multipathd
  ansible.builtin.dpkg_selections:
    name: multipath-tools
    selection: hold
  when: multipathd_installed.rc == 0
