---
# tasks file for beyerleinf.homelab.common
- name: Set timezone
  community.general.timezone:
    name: "{{ system_timezone }}"
  when: (system_timezone is defined) and (system_timezone != "Your/Timezone")

- name: Install Basic Packages
  apt:
    pkg:
      - nano
      - htop
      - openssh-server
      - qemu-guest-agent
      - iputils-ping
    state: latest
    update_cache: true

- name: Disable Snap
  import_tasks: disable-snap.yml

- name: Disable multipathd
  import_tasks: disable-multipathd.yml

- name: Create /opt/k3s directory
  ansible.builtin.file:
    path: /opt/k3s
    state: directory
    mode: 0755
