apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap
spec:
  selector:
    matchLabels:
      app: zap
  replicas: 1
  template:
    metadata:
      labels:
        app: zap
    spec:
      containers:
        - name: zap
          image: zaproxy/zap-stable
          ports:
            - containerPort: 8080
            - containerPort: 8090
          command: ["zap-webswing.sh"]

---
apiVersion: v1
kind: Service
metadata:
  name: zap
spec:
  type: NodePort
  selector:
    app: zap
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - protocol: TCP
      name: re
      port: 8090
      targetPort: 8090
      nodePort: 30090
