name: portainer
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.23.0-alpine
    ports:
      - "9000:9000"
    networks:
      - portainer
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  data:

networks:
  portainer:
    name: portainer
