name: unifi
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    restart: always
    container_name: unifi-network-application
    depends_on:
      - mongodb
    networks:
      - unifi
      - traefik
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
    volumes:
      - ${DOCKER_DIR}:/config
    environment:
      PUID: 100
      PGID: 99
      TZ: Europe/Berlin
      MONGO_USER: ${MONGODB_USERNAME}
      MONGO_PASS: ${MONGODB_PASSWORD}
      MONGO_HOST: mongodb
      MONGO_DBNAME: ${MONGODB_DB_NAME}
      MONGO_PORT: 27017
      MONGO_AUTHSOURCE: ${MONGODB_DB_NAME}
      MONGO_TLS: false
      MEM_LIMIT: 786
      MEM_STARTUP: 786
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      traefik.enable: true
      traefik.http.routers.unifi.rule: "Host(`unifi.lab.beyerleinf.de`)"
      traefik.http.routers.unifi.entrypoints: "websecure"
      traefik.http.routers.unifi.tls.certresolver: "hetzner"
      traefik.http.routers.unifi.middlewares: "unifi"
      traefik.http.services.unifi.loadbalancer.server.port: 8443
      traefik.http.services.unifi.loadbalancer.server.scheme: "https"
      traefik.http.middlewares.unifi.headers.customrequestheaders.X-Forwarded-Proto: "https"
      traefik.http.middlewares.unifi.headers.customrequestheaders.Authorization: ""

  mongodb:
    image: mongo:7.0.14
    restart: always
    networks:
      - unifi
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodbconfig:/data/configdb
      - ${DOCKER_DIR}/init.d:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_USER: ${MONGODB_USERNAME}
      MONGO_PASS: ${MONGODB_PASSWORD}
      MONGO_DBNAME: ${MONGODB_DB_NAME}
      MONGO_AUTHSOURCE: admin

volumes:
  mongodb:
  mongodbconfig:

networks:
  unifi:
    name: unifi
  traefik:
    external: true
