name: seafile
services:
  db:
    image: mariadb:11.5.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_LOG_CONSOLE: true
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - db:/var/lib/mysql
    networks:
      - seafile

  memcached:
    image: memcached:1.6.31
    restart: always
    entrypoint: memcached -m 256
    networks:
      - seafile

  seafile:
    image: seafileltd/seafile-mc:11.0-latest
    container_name: seafile
    volumes:
      - ${SEAFILE_STORAGE_PATH}:/shared
    environment:
      DB_HOST: db
      DB_ROOT_PASSWD: ${DB_ROOT_PASSWORD}
      TIME_ZONE: Europe/Berlin
      SEAFILE_ADMIN_EMAIL: ${SEAFILE_ADMIN_EMAIL}
      SEAFILE_ADMIN_PASSWORD: ${SEAFILE_ADMIN_PASSWORD}
      SEAFILE_SERVER_LETSENCRYPT: false
      SEAFILE_SERVER_HOSTNAME: files.lab.beyerleinf.de
      FORCE_HTTPS_IN_CONF: true
    depends_on:
      - db
      - memcached
    restart: always
    networks:
      - traefik
      - seafile
    labels:
      traefik.enable: true
      traefik.http.routers.seafile.rule: "Host(`files.lab.beyerleinf.de`)"
      traefik.http.routers.seafile.entrypoints: "websecure"
      traefik.http.routers.seafile.tls.certresolver: "hetzner"
      traefik.http.services.seafile.loadbalancer.server.port: 80

  db-backup:
    image: tiredofit/db-backup
    environment:
      TIMEZONE: "Europe/Berlin"
      MODE: "MANUAL"
      MANUAL_RUN_FOREVER: false
      CONTAINER_ENABLE_SCHEDULING: false
      CONTAINER_ENABLE_MONITORING: false
      BACKUP_JOB_CONCURRENCY: 1
      DEFAULT_COMPRESSION: "GZ"
      DEFAULT_GZ_RSYNCABLE: true
      DEFAULT_S3_BUCKET: ${S3_BUCKET_NAME}
      DEFAULT_S3_KEY_ID: ${S3_BUCKET_KEY_ID}
      DEFAULT_S3_KEY_SECRET: ${S3_BUCKET_KEY_SECRET}
      DEFAULT_S3_REGION: ${S3_BUCKET_REGION}
      DEFAULT_S3_HOST: ${S3_BUCKET_HOST}
      ENABLE_NOTIFICATIONS: true
      NOTIFICATION_TYPE: "MATRIX"
      MATRIX_HOST: ${MATRIX_HOST}
      MATRIX_ROOM: ${MATRIX_ROOM}
      MATRIX_ACCESS_TOKEN: ${MATRIX_ACCESS_TOKEN}
      DB01_TYPE: "mysql"
      DB01_HOST: "db"
      DB01_NAME: "ccnet_db,seahub_db,seafile_db,mysql"
      DB01_SPLIT_DB: true
      DB01_BACKUP_LOCATION: "S3"
      DB01_USER: root
      DB01_PASS: ${DB_ROOT_PASSWORD}
      DB01_S3_PATH: "db/seafile"
      DB01_CLEANUP_TIME: 40320 # 28 days
    networks:
      - seafile

networks:
  seafile:
    name: seafile
  traefik:
    name: traefik
    external: true

volumes:
  db:
