---
# tasks file for beyerleinf.homelab.svc.immich

- name: Create temp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: directory
    owner: root
    group: root
    mode: "777"
    recurse: true

- name: Ensure upload directory exists
  ansible.builtin.file:
    path: "{{ immich_upload_dir }}"
    state: directory
    owner: root
    group: root
    mode: "777"
    recurse: true

- name: Copy Docker env file
  ansible.builtin.template:
    src: files/.docker-env.j2
    dest: "{{ tmp_dir }}/.env"
    mode: "666"

- name: Copy Docker Compose file
  ansible.builtin.copy:
    src: files/docker-compose.yml
    dest: "{{ tmp_dir }}/docker-compose.yml"
    mode: "666"

- name: Copy ML HW Accel file
  ansible.builtin.copy:
    src: files/hwaccel.ml.yml
    dest: "{{ tmp_dir }}/hwaccel.ml.yml"
    mode: "666"

- name: Copy Transcoding HW Accel file
  ansible.builtin.copy:
    src: files/hwaccel.transcoding.yml
    dest: "{{ tmp_dir }}/hwaccel.transcoding.yml"
    mode: "666"

- name: Stop Immich
  community.docker.docker_compose_v2:
    project_src: "{{ tmp_dir }}"
    files:
      - docker-compose.yml
    state: stopped
    remove_volumes: true
    remove_orphans: true

- name: Deploy Immich
  community.docker.docker_compose_v2:
    project_src: "{{ tmp_dir }}"
    files:
      - docker-compose.yml
  register: output

- name: Verify that Immich is running
  ansible.builtin.assert:
    that:
      - "output.containers[0].State == 'running'"
      - "output.containers[1].State == 'running'"
      - "output.containers[2].State == 'running'"
      - "output.containers[3].State == 'running'"

- name: Remove temp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: absent
