api:
  insecure: true

providers:
  docker:
    network: traefik
    exposedByDefault: false
  file:
    directory: "/etc/traefik/conf"

entryPoints:
  websecure:
    address: ":4443"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"

certificatesResolvers:
  hetzner:
    acme:
      dnsChallenge:
        provider: "hetzner"
      email: "dev@beyerleinf.de"
      storage: "/acme/acme.json"

serversTransport:
  insecureSkipVerify: true
