global:
  scrape_interval: "1m"
  evaluation_interval: "1m"

scrape_configs:
  - job_name: "cadvisor"
    scrape_interval: "30s"
    static_configs:
      - targets:
          - "cadvisor:8080"
  - job_name: "node-exporter"
    scrape_interval: "30s"
    static_configs:
      - targets:
          - "node-exporter:9100"
  - job_name: "traefik"
    scrape_interval: "30s"
    static_configs:
      - targets:
          - "traefik:8082"
