services:
  reverse-proxy:
    image: traefik:v3.1
    container_name: traefik
    environment:
      HETZNER_API_KEY: ${HETZNER_API_KEY}
    networks:
      - traefik
    ports:
      - "4443:4443"
      - "8089:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/acme
      - ${DOCKER_DIR}/traefik.yml:/etc/traefik/traefik.yml
      - ${DOCKER_DIR}/conf/http.yml:/etc/traefik/conf/http.yml
    restart: unless-stopped

volumes:
  acme:

networks:
  traefik:
    name: traefik
