services:
  reverse-proxy:
    image: traefik:v3.2
    container_name: traefik
    environment:
      HETZNER_API_KEY: ${HETZNER_API_KEY}
    networks:
      - traefik
    ports:
      - "4443:4443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/acme
      - ${DOCKER_DIR}/traefik.yml:/etc/traefik/traefik.yml
      - ${DOCKER_DIR}/conf/http.yml:/etc/traefik/conf/http.yml
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.entrypoints: "websecure"
      traefik.http.routers.traefik.rule: "Host(`traefik.lab.beyerleinf.de`)"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.middlewares: "authentik@file"
      traefik.http.routers.traefik.tls.certresolver: "hetzner"

volumes:
  acme:

networks:
  traefik:
    name: traefik
