---
# defaults file for beyerleinf.homelab.svc.grafana

tmp_dir: "/tmp/grafana"
docker_dir: "{{ docker_base_path }}/grafana"
data_dir: "/mnt/user/grafana"
grafana_dir: "{{ docker_dir }}/grafana"
prometheus_dir: "{{ docker_dir }}/prometheus"
grafana_data_dir: "{{ data_dir }}/grafana"
prometheus_data_dir: "{{ data_dir }}/prometheus"
promtail_dir: "{{ docker_dir }}/promtail"
