---
- name: K3s Cluster Setup
  hosts: k3s_cluster
  become: true
  roles:
    - beyerleinf.homelab.common
    - xanmanning.k3s
  vars:
    k3s_etcd_datastore: false
    k3s_become: true
    k3s_server:
      disable:
        - traefik
        - coredns

- name: Download kubeconfig from master
  hosts: servers
  become: true
  tasks:
    - name: Copy kubeconfig from master
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./kubeconfig.yml
        flat: yes
      run_once: true
      when: inventory_hostname == groups['servers'][0]
