---
- name: Deploy
  hosts: arya
  become: true
  gather_facts: false
  roles:
    - { role: beyerleinf.homelab.common, tags: ["always"] }
    - { role: beyerleinf.homelab.svc.hetzner-ddns, tags: ["infra"] }
    - { role: beyerleinf.homelab.svc.authentik, tags: ["infra"] }
    - { role: beyerleinf.homelab.svc.traefik, tags: ["infra"] }
    - { role: beyerleinf.homelab.svc.portainer, tags: ["infra"] }
    - { role: beyerleinf.homelab.svc.homepage, tags: ["homepage"] }
    - { role: beyerleinf.homelab.svc.paperless-ngx, tags: ["paperless"] }
    - { role: beyerleinf.homelab.svc.umami, tags: ["umami"] }
    - { role: beyerleinf.homelab.svc.jellyfin, tags: ["jellyfin"] }
    - { role: beyerleinf.homelab.svc.seafile, tags: ["seafile"] }
    - { role: beyerleinf.homelab.svc.immich, tags: ["immich"] }
    - { role: beyerleinf.homelab.svc.vault, tags: ["vault"] }
    - { role: beyerleinf.homelab.svc.deluge, tags: ["deluge"] }
    - { role: beyerleinf.homelab.svc.servarr, tags: ["servarr"] }
    - { role: beyerleinf.homelab.svc.pihole, tags: ["pihole"] }
    - { role: beyerleinf.homelab.svc.unifi, tags: ["unifi"] }
    - { role: beyerleinf.homelab.svc.tube-archivist, tags: ["tubearchivist"] }
    - { role: beyerleinf.homelab.svc.grafana, tags: ["grafana"] }
    - { role: beyerleinf.homelab.svc.homeassistant, tags: ["hass"] }
    - { role: beyerleinf.homelab.svc.webhook, tags: ["webhook"] }
    - { role: beyerleinf.homelab.svc.filebrowser, tags: ["filebrowser"] }
    - { role: beyerleinf.homelab.svc.minecraft-server, tags: ["mcs"] }
    - { role: beyerleinf.homelab.svc.frigate, tags: ["frigate"] }

- name: After All tasks
  hosts: arya
  tags: always
  gather_facts: false
  become: true
  tasks:
    - name: Prune dangling images
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: true
