---
- name: Common settings
  hosts: arya
  tags: always
  become: true
  roles:
    - beyerleinf.homelab.common

- name: Deploy Infrastructure
  hosts: arya
  tags: infrastructure
  become: true
  roles:
    - beyerleinf.homelab.svc.hetzner-ddns
    - beyerleinf.homelab.svc.authentik
    - beyerleinf.homelab.svc.traefik
    - beyerleinf.homelab.svc.portainer

- name: Deploy Homepage
  hosts: arya
  tags: homepage
  become: true
  roles:
    - beyerleinf.homelab.svc.homepage

- name: Deploy Paperless-ngx
  hosts: arya
  tags: paperless
  become: true
  roles:
    - beyerleinf.homelab.svc.paperless-ngx

- name: Deploy Umami
  hosts: arya
  tags: umami
  become: true
  roles:
    - beyerleinf.homelab.svc.umami

- name: Deploy Jellyfin
  hosts: arya
  tags: jellyfin
  become: true
  roles:
    - beyerleinf.homelab.svc.jellyfin

- name: Deploy Seafile
  hosts: arya
  tags: seafile
  become: true
  roles:
    - beyerleinf.homelab.svc.seafile

- name: Deploy Immich
  hosts: arya
  tags: immich
  become: true
  roles:
    - beyerleinf.homelab.svc.immich

- name: Deploy Vault
  hosts: arya
  tags: vault
  become: true
  roles:
    - beyerleinf.homelab.svc.vault

- name: Deploy Deluge
  hosts: arya
  tags: deluge
  become: true
  roles:
    - beyerleinf.homelab.svc.deluge

- name: Deploy Servarr
  hosts: arya
  tags: servarr
  become: true
  roles:
    - beyerleinf.homelab.svc.servarr

- name: Deploy PiHole
  hosts: arya
  tags: pihole
  become: true
  roles:
    - beyerleinf.homelab.svc.pihole

- name: Deploy UniFi
  hosts: arya
  tags: unifi
  become: true
  roles:
    - beyerleinf.homelab.svc.unifi

- name: Deploy Actual
  hosts: arya
  tags: actual
  become: true
  roles:
    - beyerleinf.homelab.svc.actual-budget

- name: Deploy Firefly III
  hosts: arya
  tags: firefly
  become: true
  roles:
    - beyerleinf.homelab.svc.firefly

- name: Deploy TubeArchivist
  hosts: arya
  tags: tubearchivist
  become: true
  roles:
    - beyerleinf.homelab.svc.tube-archivist

- name: Deploy Grafana
  hosts: arya
  tags: grafana
  become: true
  roles:
    - beyerleinf.homelab.svc.grafana
