---
- name: Deploy Infrastructure
  hosts: arya
  become: true
  roles:
    - beyerleinf.homelab.svc.hetzner-ddns
    - beyerleinf.homelab.svc.traefik

- name: Deploy Services
  hosts: arya
  become: true
  roles:
    - beyerleinf.homelab.svc.homepage
    - beyerleinf.homelab.svc.paperless-ngx
    - beyerleinf.homelab.svc.umami
