---
# tasks file for beyerleinf.homelab.svc.homepage

- name: Create temp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: directory
    owner: root
    group: root
    mode: "666"
    recurse: true

- name: Copy Docker env file
  ansible.builtin.template:
    src: files/.docker-env.j2
    dest: "{{ tmp_dir }}/.env"
    mode: "666"

- name: Copy Docker Compose file
  ansible.builtin.copy:
    src: files/docker-compose.yml
    dest: "{{ tmp_dir }}/docker-compose.yml"
    mode: "666"

- name: Stop Homepage
  community.docker.docker_compose_v2:
    project_src: "{{ tmp_dir }}"
    files:
      - docker-compose.yml
    state: stopped
    remove_volumes: true

- name: Delete old Docker directory
  ansible.builtin.file:
    state: absent
    path: "{{ docker_dir }}"

- name: Create Docker directory
  ansible.builtin.file:
    path: "{{ docker_dir }}"
    state: directory
    owner: root
    group: root
    mode: "666"
    recurse: true

- name: Copy Homepage settings
  ansible.builtin.template:
    src: files/settings.yml.j2
    dest: "{{ docker_dir }}/settings.yaml"
    mode: "666"

- name: Copy Homepage services
  ansible.builtin.template:
    src: files/services.yml.j2
    dest: "{{ docker_dir }}/services.yaml"
    mode: "666"

- name: Copy Homepage docker config
  ansible.builtin.template:
    src: files/docker.yml.j2
    dest: "{{ docker_dir }}/docker.yaml"
    mode: "666"

- name: Deploy Homepage
  community.docker.docker_compose_v2:
    project_src: "{{ tmp_dir }}"
    files:
      - docker-compose.yml
  register: output

- name: Verify that Homepage is running
  ansible.builtin.assert:
    that:
      - "output.containers[0].State == 'running'"

- name: Remove temp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: absent
