name: servarr
services:
  flaresolverr:
    container_name: flaresolverr
    restart: always
    image: binhex/arch-flaresolverr:3.3.21-1-02
    ports:
      - "8191:8191"
    networks:
      - deluge
    volumes:
      - ${FLARESOLVERR_DIR}:/config
    environment:
      UMASK: 000
      PUID: 99
      PGID: 100

  prowlarr:
    container_name: prowlarr
    restart: always
    image: binhex/arch-prowlarr:1.28.2.4885-1-01
    ports:
      - "9696:9696"
    networks:
      - deluge
    volumes:
      - ${PROWLARR_DIR}:/config
    environment:
      UMASK: 000
      PUID: 99
      PGID: 100

  sonarr:
    container_name: sonarr
    restart: always
    image: binhex/arch-sonarr:4.0.11.2680-1-01
    ports:
      - "8989:8989"
      - "9897:9897"
    networks:
      - deluge
    volumes:
      - ${TVSHOWS_DIR}:/media
      - ${DELUGE_DIR}:/data
      - ${SONARR_DIR}:/config
    environment:
      UMASK: 000
      PUID: 99
      PGID: 100

  radarr:
    container_name: radarr
    restart: always
    image: binhex/arch-radarr:5.15.1.9463-1-01
    ports:
      - "7878:7878"
    networks:
      - deluge
    volumes:
      - ${MOVIES_DIR}:/media
      - ${DELUGE_DIR}:/data
      - ${RADARR_DIR}:/config
    environment:
      UMASK: 000
      PUID: 99
      PGID: 100

  lidarr:
    container_name: lidarr
    restart: always
    image: binhex/arch-lidarr:2.5.3.4341-1-02
    ports:
      - "8686:8686"
    networks:
      - deluge
    volumes:
      - ${MUSIC_DIR}:/media
      - ${DELUGE_DIR}:/data
      - ${LIDARR_DIR}:/config
    environment:
      UMASK: 000
      PUID: 99
      PGID: 100

networks:
  deluge:
    external: true
