# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/24 # local subnet
    - 172.19.0.0/24 # traefik subnet

waste_collection_schedule: !include waste_schedule.yaml

sensor:
  - platform: waste_collection_schedule
    name: "Waste Schedule"
