---
# tasks file for beyerleinf.homelab.svc.paperless-ngx

- name: Create temp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: directory
    owner: root
    group: root
    mode: "666"
    recurse: true

- name: Ensure docker directory exists
  ansible.builtin.file:
    path: "{{ docker_dir }}"
    state: directory
    owner: root
    group: root
    mode: "666"
    recurse: true

- name: Ensure media directory exists
  ansible.builtin.file:
    path: "{{ docker_dir }}/media"
    state: directory
    owner: root
    group: root
    mode: "666"
    recurse: true

- name: Ensure export directory exists
  ansible.builtin.file:
    path: "{{ docker_dir }}/export"
    state: directory
    owner: root
    group: root
    mode: "666"
    recurse: true

- name: Copy Docker env file
  ansible.builtin.template:
    src: files/.docker-env.j2
    dest: "{{ tmp_dir }}/.env"
    mode: "666"

- name: Copy Docker Compose file
  ansible.builtin.copy:
    src: files/docker-compose.yml
    dest: "{{ tmp_dir }}/docker-compose.yml"
    mode: "666"

- name: Stop Paperless-ngx
  community.docker.docker_compose_v2:
    project_src: "{{ tmp_dir }}"
    files:
      - docker-compose.yml
    state: absent
    remove_volumes: true

- name: Delete old Docker directory
  ansible.builtin.file:
    state: absent
    path: "{{ docker_dir }}"

- name: Create Docker directory
  ansible.builtin.file:
    path: "{{ docker_dir }}"
    state: directory
    owner: root
    group: root
    mode: "666"
    recurse: true

- name: Deploy Paperless-ngx
  community.docker.docker_compose_v2:
    project_src: "{{ tmp_dir }}"
    files:
      - docker-compose.yml
  register: output

- name: Verify that Paperless-ngx is running
  ansible.builtin.assert:
    that:
      - "output.containers[0].State == 'running'"

- name: Remove temp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: absent
